version: 1

defaults:
#  stopIfNotBranchHead: false
  timeoutInMinutes: 10
  image: 'aws/codebuild/nodejs:8.11.0'
  environmentVariables:
    - name: SLEEP_TIME
      value: "60"

builds:
  lint:
    commitStatus: awsbuild/linting-slow
    environmentVariables:
      - name: SLEEP_TIME
        value: "60"
