version: 1

defaults:
#  stopIfNotBranchHead: false
  timeoutInMinutes: 10
  image: 'aws/codebuild/nodejs:8.11.0'
  useCache: true
  environmentVariables:
    - name: SLEEP_TIME
      value: "10"

builds:
  lint:
    commitStatus: awsbuild/linting-slow
