version: 0.2
phases:
  install:
    commands:
      - echo install
      - sleep $SLEEP_TIME
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - echo build
  post_build:
    commands:
      - echo post_build
artifacts:
  files: '**/*'
  base-directory: artifacts
