version: 0.2
phases:
  install:
    commands:
      - echo install
      - false
  pre_build:
    commands:
      - echo pre_build
      - false
  build:
    commands:
      - echo build
      - false
  post_build:
    commands:
      - echo post_build
      - false
artifacts:
  files: '**/*'
  base-directory: artifacts
