version: 0.2
phases:
  install:
    commands:
      - echo install
      - sleep $SLEEP_TIME
      - echo npm config get cache --global
  pre_build:
    commands:
      - echo pre_build
      - mkdir artifacts
  build:
    commands:
      - echo build
      - echo Foobar1 > builda.dat
      - echo Foobar2 > artifacts/buildb.dat
      - echo Foobar3 > artifacts/buildc.dat
  post_build:
    commands:
      - echo post_build
artifacts:
  files: '**/*'
  base-directory: artifacts
