version: 0.2
phases:
  install:
    commands:
      - npm install --cache-min=9999
      - mkdir artifacts
      - mkdir build
  build:
    commands:
      - npm run -s build
      - tar -zcf build/app.tar.gz app/*.js
  post_build:
    commands:
      - mv build artifacts
cache:
  paths:
    - '/root/.npm/**/*'
    - 'node_modules/**/*'
artifacts:
  files: '**/*'
  base-directory: artifacts
